source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf

################
### MONITORS ###
################

monitor=,preferred,auto,auto
monitor=DP-1,1920x1080@239.96Hz,auto,auto

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20
env = HYPRCURSOR_THEME,NotwaitaBlack

# NVIDIA wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

env = GTK_THEME,Adwaita:dark
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,Adwaita-Dark
env = QT_STYLE_OVERRIDE,Adwaita-Dark

env = SDL_AUDIODRIVER,pipewire
env = SDL_VIDEODRIVER,wayland

#################
### AUTOSTART ###
#################

exec-once = pidof waybar; if [ $? -eq 1 ]; then waybar & disown; fi
exec-once = [workspace 10 silent] sleep 10 && obs --startreplaybuffer &

#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 1
    gaps_out = 0

    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(00ff00ff)
    col.inactive_border = rgba(595959ff)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = true

    layout = scrolling
}

decoration {
    rounding = 0
    rounding_power = 0

    shadow:enabled = false
    blur:enabled = false
}

animations:enabled = no #yes, please :)

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

scrolling {
    explicit_column_widths = 0.5, 1.0
    focus_fit_method = 1
}

misc {
    disable_autoreload = true
    force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vrr = 0
    background_color = 0x000000
}

#############
### INPUT ###
#############

input {
    kb_layout = us

    repeat_rate = 80
    repeat_delay = 200

    follow_mouse = 0
    float_switch_override_focus = 0
    mouse_refocus = false

    sensitivity = 0
    accel_profile = flat

    touchpad:natural_scroll = false
}

cursor {
    hide_on_key_press = true
    no_warps = true
}

gesture = 3, horizontal, workspace
