general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = false
}

background {
    path =
    color = rgba(0, 0, 0, 1.0)
}

label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 120
    font_family = Unifont

    position = 0, 25%
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "$(date +"%Y-%m-%d")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 50
    font_family = Unifont

    position = 0, 12.5%
    halign = center
    valign = center
}

input-field {
    position = 0, 0
    halign = center
    valign = center

    fade_on_empty = false

    placeholder_text =
    dots_size = 1

    size = 100%, 7%

    inner_color = rgba(5, 5, 5, 1.0)
    check_color = rgba(255, 255, 0, 1.0)
    outline_thickness = 0
    rounding = 0
}
