general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = false
}

input-field {
    position = 0, 0
    halign = center
    valign = center

    fade_on_empty = false

    placeholder_text =
    dots_size = 1

    size = 100%, 7%

    inner_color = rgba(5, 5, 5, 1.0)
    check_color = rgba(255, 255, 0, 1.0)
    outline_thickness = 0
    rounding = 0
}
