profile = high-quality
keep-open = yes
force-window = immediate
save-position-on-quit = yes
cache = yes
demuxer-max-bytes = 4000000
demuxer-max-back-bytes = 1000000

ytdl-format = bestvideo+bestaudio

screenshot-dir = ~/Pictures/mpv
screenshot-format = png
screenshot-high-bit-depth = yes
screenshot-template = "%F-%p-%n"

alang = jpn,ja,eng,en
slang = eng,en
