[colors]
background=000000

# 4-bit colors
regular0=000000  # black
regular1=aa0000  # red
regular2=00aa00  # green
regular3=aa5500  # yellow (rendered as brown in CGA)
regular4=0000aa  # blue
regular5=aa00aa  # magenta
regular6=00aaaa  # cyan
regular7=aaaaaa  # white (light gray)

bright0=555555   # bright black (dark gray)
bright1=ff5555   # bright red
bright2=55ff55   # bright green
bright3=ffff55   # bright yellow
bright4=5555ff   # bright blue
bright5=ff55ff   # bright magenta
bright6=55ffff   # bright cyan
bright7=ffffff   # bright white

[main]
font=Unifont:size=12
initial-window-size-pixels=1280x720

[scrollback]
lines=100000

[mouse]
hide-when-typing=yes
